version: "3"
services:
  mysqldb:
    image: mysql:8.3.0
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=Etudiant_MS
    ports:
      - "3306:3306"
    networks:
      - ms
    volumes:
      - mysql-db:/data/mysqldb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/mongodb
    networks:
      - ms

  config-server:
    image: omarito47/configserver:0.0.1
    container_name: configserver
    restart: always
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      - spring_cloud_config_server_git_uri=${GIT_URI}
      - spring_cloud_config_server_git_username=${GIT_USERNAME}
      - spring_cloud_config_server_git_password=${GIT_TOKEN}
    volumes:
      - config-server:/config-server
    networks:
      - ms

  discovery-server:
    #    depends_on:
    #      - config-server
    image: omarito47/discoveryserver:0.0.1
    container_name: discoveryserver
    restart: always
    ports:
      - 8761:8761
    volumes:
      - discovery-server:/discovery-server
    networks:
      - ms
  etudiant-ms:
    depends_on:
      - mysqldb
      - config-server
    image: omarito47/ms1etudiant:0.0.1
    container_name: ms1etudiant
    restart: always
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/ms1etudiant?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - spring.jpa.hibernate.ddl-auto=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.config.import=optional:configserver:http://config-server:8888
    networks:
      - ms

  foyer-ms:
    depends_on:
      - mongodb
      - config-server
    image: omarito47/ms2foyer:0.0.1
    container_name: ms2foyer
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/foyerdb
      - spring.data.mongodb.database=foyerdb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888/
    networks:
      - ms

  gateway-api:
    image: omarito47/gatewayservice:0.0.1
    container_name: gatewayservice
    restart: always
    ports:
      - 9090:9090
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - ms

volumes:
  mysql-db:
  mongodb:
  ms1etudiant:
  ms2foyer:
  gateway-api:
  discovery-server:
  config-server:

networks:
  ms:

